/**
 * Catalogue expansion: jade and jewellery pieces.
 *
 * These departments differ from tea in one way that matters: they have no
 * photograph. Every piece here is drawn by the house illustrator and carries the
 * "illustration" disclosure, because a photograph of somebody else's bangle
 * presented as this shop's stock would be a misdescription of the goods.
 *
 * The rows are deliberately structured as **form × material**, which is how a
 * jade or jewellery dealer actually thinks and how a customer actually shops:
 * a bangle buyer chooses the form first and the stone second. Each row supplies
 * the hook — the one specific thing about that piece — and the builder composes
 * the rest from the material and form notes, so the copy is specific rather than
 * a template with the noun swapped.
 *
 * Prices sit in the range the shop already publishes for these departments,
 * CAD 300 to 10,000, and they scale from the material, which is what genuinely
 * drives price in both trades.
 */

/* -------------------------------------------------------------------------- */
/*  Jade                                                                      */
/* -------------------------------------------------------------------------- */

/** What each stone is, where it comes from, and what it costs. */
export const JADE_MATERIALS = {
  hetian_white: {
    name: 'Hetian white nephrite',
    origin: 'Hetian, Xinjiang',
    mult: 1,
    copy: 'Hetian nephrite is the stone the Chinese have called jade for four thousand years: dense, waxy and white rather than the vivid green most Western buyers picture, which is jadeite. Carvers prize it because it holds a fine edge and takes a soft polish without turning glassy.',
    price: 310,
  },
  mutton_fat: {
    name: 'mutton-fat nephrite',
    origin: 'Hetian, Xinjiang',
    mult: 2.1,
    copy: 'Mutton-fat is the top grade of Hetian white: not pure white but a warm, faintly creamy tone with a greasy surface lustre, like a piece of chilled fat. It is the grade Chinese collectors have argued about for centuries, it comes from a small part of one riverbed, and a genuine piece is priced accordingly.',
    price: 980,
  },
  spinach_green: {
    name: 'spinach-green nephrite',
    origin: 'Manas, Xinjiang',
    mult: 0.94,
    copy: 'Spinach-green nephrite is deep, even and almost opaque, closer to a dark celadon than to emerald. It is the colour most traditional Chinese carvings are made in, it takes an unusually high polish, and it is the most affordable way into real nephrite.',
    price: 300,
  },
  yellow_nephrite: {
    name: 'yellow nephrite',
    origin: 'Ruoxiang, Xinjiang',
    mult: 1.7,
    copy: 'Yellow nephrite is scarce — rarer than white in any given year, because the deposit is small and the colour only appears in part of it. The tone runs from a pale honey to a deep amber, and carvers work around the darker patches rather than cutting them away, since the colour is the point.',
    price: 720,
  },
  black_nephrite: {
    name: 'black nephrite (Dark Jade)',
    origin: 'Hetian, Xinjiang',
    mult: 1.24,
    copy: 'Black nephrite is not black like ink but black like deep water: hold it to a strong light and the edges glow green. It is dense, quiet and unusually good in the hand, and it is the nephrite that shows a carver\'s line most clearly because there is no colour to hide behind.',
    price: 520,
  },
  jadeite_apple: {
    name: 'apple-green jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.3,
    copy: 'Apple-green jadeite is bright, evenly saturated and translucent enough to glow at the edges. Jadeite is the harder, later-arriving stone — it only entered Chinese use in the eighteenth century — and it is graded on transparency before colour, which is why two stones of the same shade can differ tenfold in price.',
    price: 640,
  },
  jadeite_lavender: {
    name: 'lavender jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.46,
    copy: 'Lavender jadeite, the Chinese "spring colour", is notoriously difficult to photograph: it looks washed out under most light and only comes alive in daylight, which is why a dealer will always walk a lavender piece to the window. The hue is stable if the piece is worn and fades if it is left in strong sun.',
    price: 780,
  },
  jadeite_ice: {
    name: 'ice-type jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.72,
    copy: 'Ice-type is graded on how much light passes through it, not on its colour: the stone is nearly colourless, finely crystalline and translucent enough to read a printed page through a thin section. It is the grade that shows a carving at its best, because there is nothing in the stone to distract from the line.',
    price: 1150,
  },
  jadeite_moss: {
    name: 'moss-in-snow jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.54,
    copy: 'Moss-in-snow, or floating flower, is a translucent white body threaded with patches of green. No two pieces are alike, the pattern cannot be planned, and the skill is in cutting so the green falls where it flatters the carving rather than where it happens to sit.',
    price: 890,
  },
  jadeite_imperial: {
    name: 'imperial-green jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 6.4,
    copy: 'Imperial green is the top of the jadeite market: a deep, saturated, slightly blue-leaning green with enough translucency to look lit from within. The name is a trade convention rather than a formal grade, the supply is a few stones a year, and it is the one jade where the price really is in the stone.',
    price: 3200,
  },
  jadeite_white: {
    name: 'white jadeite',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.12,
    copy: 'White jadeite is coarser and less waxy than Hetian nephrite but harder and noticeably brighter, with a sparkle rather than a sheen. It is the stone most modern Chinese jewellery is set with, and it holds a crisp edge that nephrite cannot.',
    price: 430,
  },
};

/** What each form is, and what to know before buying it. */
export const JADE_FORMS = {
  bangle_round: {
    name: 'round-section bangle',
    copy: 'A bangle is cut as a complete circle from a core drilled out of a boulder, which is why the colour runs continuously around it and why the size cannot be altered afterwards. The round profile is the traditional one: comfortable, and the form that shows the evenness of the stone best.',
    care: 'Measure your wrist against the inner diameter before ordering; a bangle is bought once.',
    unit: 'Bangle',
  },
  bangle_oval: {
    name: 'oval-section bangle',
    copy: 'The oval profile follows the shape of the wrist rather than the shape of the drill core, so it sits closer and moves less. It is easier to put on than a round bangle of the same inner measurement, which is why it is the profile most people actually wear.',
    care: 'Oval bangles are sized on the long axis; ask us for the inner measurement before ordering.',
    unit: 'Bangle',
  },
  bangle_princess: {
    name: 'princess (flat) bangle',
    copy: 'A princess bangle is flat on the inside and outside with square edges, which wastes less stone than any other profile and therefore gives more bangle for the same boulder. It is the modern cut: crisper, more architectural, and unforgiving of a rough polish.',
    care: 'The square edge is the first place to show a knock; store it in the box it arrives in.',
    unit: 'Bangle',
  },
  pendant_buddha: {
    name: 'Buddha pendant',
    copy: 'A seated Buddha is the most traditional pendant form in Chinese jade and the one most often given as a gift, worn for protection rather than ornament. The carving follows the shape of the stone, which is why no two are the same height.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_guanyin: {
    name: 'Guanyin pendant',
    copy: 'Guanyin, the bodhisattva of compassion, is carved standing or seated and is traditionally worn by women as the Buddha is by men. The face is the whole piece: a good carver makes it serene and a poor one makes it blank, and the difference is visible from across a room.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_gourd: {
    name: 'gourd pendant',
    copy: 'The double gourd is a rebus for good fortune and protection, its shape following two spheres of the same stone. It is the simplest form in the repertoire to carve badly and one of the hardest to carve well, because there is nowhere to hide an uneven curve.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_coin: {
    name: 'coin pendant',
    copy: 'A jade coin with a square hole is the oldest amulet form in China: the disc is heaven and the square is earth, and the shape predates the currency it resembles. It is the piece most often worn by people who want jade without wanting to explain it.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_bat_coin: {
    name: 'bat and coin pendant',
    copy: 'A bat over a coin is a visual pun: "bat" and "blessing" are the same word in Chinese, and a coin over a bat reads as blessings arriving. It is a piece full of meaning that looks like a piece of geometry, which is the point of the whole tradition.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_peach: {
    name: 'peach pendant',
    copy: 'The peach is the symbol of long life, and a jade peach is given on birthdays rather than bought. The carver works with the natural colour of the stone: a patch of pale colour becomes the blush on the fruit instead of being cut away.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_lotus: {
    name: 'lotus pendant',
    copy: 'The lotus rises out of mud and opens clean, which is why it stands for purity, and a jade lotus is the pendant most often worn by women who wear jade daily rather than on occasion. The petals are carved thin enough to catch the light through the stone.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  pendant_phoenix: {
    name: 'phoenix pendant',
    copy: 'The phoenix is the female counterpart to the dragon and traditionally worn with it, so a phoenix pendant is often bought as half of a pair. The tail is where the carver shows off: it takes more openwork than any other form here.',
    care: 'Openwork is thin by design; store it flat rather than hanging.',
    unit: 'Pendant',
  },
  pendant_cicada: {
    name: 'cicada pendant',
    copy: 'The cicada is the oldest jade amulet of all — pieces two thousand years old take the same form — because it lives underground for years and emerges to sing. In a translucent stone the wings are carved paper-thin so they disappear when held to the light.',
    care: 'The wings are deliberately thin; keep it away from keys and clasps.',
    unit: 'Pendant',
  },
  pendant_bamboo: {
    name: 'bamboo section pendant',
    copy: 'A bamboo section is carved as a hollow tube with nodal rings, standing for integrity and steady growth. It is a shape that only works in a stone with no flaws in it, because the tube has to be cut from solid material and any fracture shows.',
    care: 'Wear it against the skin; nephrite deepens with handling.',
    unit: 'Pendant',
  },
  bi_disc: {
    name: 'bi disc',
    copy: 'The bi disc is a flat annulus with a central hole, and it is the form on which Chinese jade carving was founded: examples survive from before the invention of the wheel. It is carved plain or with a grain pattern, and it is as much a sculpture to keep on a desk as a thing to wear.',
    care: 'Display it on a stand rather than a chain; the flat face shows every knock.',
    unit: 'Disc',
  },
  bead_strand: {
    name: 'bead strand / mala',
    copy: 'A bead strand is graded on consistency rather than on any single bead: the colour, the translucency and the diameter have to match from the first bead to the last, which means cutting far more beads than are used. A 108-bead mala is the traditional count and takes a genuinely large stone to make.',
    care: 'Restring every few years if worn daily; silk stretches.',
    unit: 'Strand',
  },
  bead_bracelet: {
    name: 'bead bracelet',
    copy: 'A bead bracelet uses the same grading discipline as a mala on a shorter strand, so it is graded on how closely the beads match rather than on the size of any one of them. The beads roll as you move, which is the whole appeal of the form.',
    care: 'Restring if the cord shows wear; jade beads are heavy for their size.',
    unit: 'Bracelet',
  },
  archers_ring: {
    name: "archer's ring",
    copy: "An archer's ring was a working tool before it was jewellery: a jade cylinder worn on the thumb to protect the string hand, in use for three thousand years. It is now worn as a thumb ring, and the form is unusual enough to be a piece people ask about.",
    care: 'Sold by inner diameter; a working ring should be snug on the thumb.',
    unit: 'Ring',
  },
  dome_ring: {
    name: 'dome ring',
    copy: 'A jade dome ring sets a single cabochon high on a plain band, which puts the stone where the light hits it and where the hand moves. It is the jade ring that reads as contemporary jewellery rather than as a curio.',
    care: 'Have it sized by a jeweller; jade does not bend.',
    unit: 'Ring',
  },
  signet_seal: {
    name: 'signet seal',
    copy: 'A seal is a piece of jade with your name cut into the base, and it was for centuries the way a Chinese official signed anything. The stone must be flawless where the face is cut, because a fault in the base produces a broken imprint every time it is used.',
    care: 'Keep the face dry and away from ink solvents; we can recut the seal face.',
    unit: 'Seal',
  },
  pair_seal: {
    name: 'pair of seals',
    copy: 'A pair of seals — one for a name, one for a studio or a phrase — is the traditional desk set, cut from a single block so the two stones match in tone. Buying a pair guarantees a colour match that buying two singles never does.',
    care: 'Keep the faces dry; store the pair upright in their box.',
    unit: 'Pair',
  },
  figure_horse: {
    name: 'horse figure',
    copy: 'A jade horse is a scholar\'s object rather than a charm: the carving is judged on the line of the neck and the set of the legs, and a good one looks like it is about to move. It is the piece most often bought as a desk piece for someone else.',
    care: 'Desk piece; keep it on felt rather than a hard shelf.',
    unit: 'Figure',
  },
  figure_crane: {
    name: 'crane figure',
    copy: 'The crane stands for long life and, on a piece of jade, for the patience of the carver: the legs are cut as thin as the stone will allow and are the first thing to break. It is a carving that shows the quality of the material, because thin sections have to be flawless.',
    care: 'The legs are the weak point; lift it by the body.',
    unit: 'Figure',
  },
  figure_lion: {
    name: 'guardian lion figure',
    copy: 'A guardian lion on a plinth is the piece that sits at the corner of a desk facing the door, in the Chinese domestic tradition rather than the Buddhist one. The carving is deliberately dense, so it uses a stone with flaws that a pendant could not.',
    care: 'Desk piece; heavy for its size and stable on its plinth.',
    unit: 'Figure',
  },
  figure_immortal: {
    name: 'immortal figure',
    copy: 'One of the Eight Immortals, carved standing with their attribute — a fan, a gourd, a sword — and each one carrying its own meaning. Figures are the hardest test of a carver, because a face and a hand at this scale cannot be fixed afterwards.',
    care: 'Desk piece; keep it out of direct sun so the tone stays even.',
    unit: 'Figure',
  },
  toad_on_leaf: {
    name: 'toad on a lotus leaf',
    copy: 'The three-legged toad sits on a lotus leaf and spits coins, which is the most mercantile of all the jade rebuses and the one most often put on a shop counter. The leaf is carved thin and veined; the toad is dense and rounded, so the piece plays with two different weights of stone.',
    care: 'Desk piece; the leaf edge is thin.',
    unit: 'Figure',
  },
  mountain_carving: {
    name: 'mountain carving (shanzi)',
    copy: 'A shanzi uses the whole boulder: the carver reads the flaws, the colour bands and the shape of the raw stone and then decides what landscape is already in it. Nothing is wasted and nothing is imposed, which is why a good shanzi is the most respected form in the repertoire.',
    care: 'Substantial piece; display it where it can be seen from more than one side.',
    unit: 'Carving',
  },
  landscape_plaque: {
    name: 'landscape plaque',
    copy: 'A plaque is cut flat from a slab and carved in shallow relief, which is the form that suits a stone with a strong colour band running through it: the band becomes a river or a ridge line and the carving follows the stone rather than fighting it.',
    care: 'Display flat or on a stand; the relief is shallow and can be worn by cleaning.',
    unit: 'Plaque',
  },
  cup: {
    name: 'cup',
    copy: 'A jade cup is thin-walled, which is the hardest thing to cut in this material and the reason a good one costs what it does: the wall has to be translucent enough to glow and thick enough to survive a hand. It is meant to be drunk from, not shelved.',
    care: 'Hand wash only, no detergent, no sudden temperature change.',
    unit: 'Cup',
  },
  cup_pair: {
    name: 'pair of cups',
    copy: 'Two cups cut from one block so the tone and the wall thickness match, which is much harder than cutting one. A pair is the traditional gift for a wedding or a new business, and the two are meant to be used together.',
    care: 'Hand wash only; never pour boiling water into a cold cup.',
    unit: 'Pair',
  },
  snuff_bottle: {
    name: 'snuff bottle',
    copy: 'The snuff bottle is a Qing dynasty form that became a serious collecting category in its own right: small enough for a sleeve, hollowed through a hole no wider than a finger, and judged on the evenness of the interior hollow. It is a virtuoso object first and a container second.',
    care: 'Keep the stopper seated; the spoon is bone and dislikes water.',
    unit: 'Bottle',
  },
  belt_buckle: {
    name: 'belt buckle',
    copy: 'A jade belt buckle was a rank marker in the Ming and Qing courts and is now worn on a plain leather belt, which is the least fussy way to wear a large piece of stone. The form is cut as two interlocking halves joined by a hook.',
    care: 'Check the hook tension before wearing it on a belt.',
    unit: 'Buckle',
  },
  hairpin: {
    name: 'hairpin',
    copy: 'A jade hairpin is carved as a single tapering rod with the ornament at the head, and the rod is the difficult part: it has to be straight and unflawed for its whole length, which means most stones are rejected before carving begins.',
    care: 'The shaft is thin; store it in the box rather than loose.',
    unit: 'Hairpin',
  },
  earrings_drop: {
    name: 'drop earrings',
    copy: 'A matched pair of drops, cut from adjacent slices of the same stone so the colour matches at a glance. Because light passes through a drop rather than reflecting off it, the pair reads brighter and greener than a pendant cut from the same block.',
    care: 'Jade drops are set on posts; remove them before sport.',
    unit: 'Earrings',
  },
  earrings_huggie: {
    name: 'huggie earrings',
    copy: 'Small hoops set with jadeite, sized to sit close against the lobe so the stone is lit from behind by the ear. It is the form that makes a dark or highly translucent stone look its best, and the pair most often worn continuously.',
    care: 'Fixed posts with butterfly backs; check the setting monthly.',
    unit: 'Earrings',
  },
  pendant_chain_set: {
    name: 'pendant and chain set',
    copy: 'A pendant cut to hang from a chain threaded through its own bail, so nothing about the setting competes with the stone. The bail is drilled rather than glued, which is the traditional way and the one that lasts.',
    care: 'Restring the chain every few years; silk stretches with wear.',
    unit: 'Set',
  },
  cong_tube: {
    name: 'cong tube',
    copy: 'The cong is a square tube with a round bore, one of the two founding forms of Chinese jade alongside the bi disc, and its original meaning is unknown. It is carved with simplified faces at the corners and is an object for a collector rather than for wear.',
    care: 'Display upright on a stand; the bore is unpolished by design.',
    unit: 'Tube',
  },
  axe_blade: {
    name: 'ceremonial axe (fu)',
    copy: 'A jade axe is the oldest ceremonial form here: a flat blade with a hafting hole, too soft in this stone to have ever cut anything, which is exactly why it was ceremonial. It is a striking graphic object and a serious collector\'s form.',
    care: 'The blade edge is thin; display it flat rather than standing.',
    unit: 'Blade',
  },
  dragon_hook: {
    name: 'dragon hook',
    copy: 'A dragon hook is an S-curved shaft ending in a dragon head, originally a belt fastener and now kept as a desk piece. It is the form that shows a carver\'s skill at depth, because the curve has to be cut from straight material.',
    care: 'Desk piece; lift it by the shaft rather than the head.',
    unit: 'Hook',
  },
  pendant_imperial: {
    name: 'imperial-green pendant',
    copy: 'A single drop of imperial-green jadeite, cut as a plain cabochon with no carving at all, because at this grade the stone is the work. Anything cut into it would remove colour, and colour is what is being paid for.',
    care: 'The stone is the value; have the setting checked annually.',
    unit: 'Pendant',
  },
};

/** form_key, material_key, name, hook, plus optional size/price overrides. */
export const JADE_ROWS = [
  { form: 'pendant_guanyin', material: 'hetian_white', name: 'Guanyin Pendant', seal: 'Guanyin',
    hook: 'A seated Guanyin with the face carved first and everything else built around it, from one piece of white nephrite.' },
  { form: 'pendant_gourd', material: 'mutton_fat', name: 'Mutton-Fat Gourd Pendant', seal: 'Gourd',
    hook: 'Two even spheres from a stone that is warm rather than white — the grade Chinese collectors spend decades arguing about.' },
  { form: 'pendant_coin', material: 'spinach_green', name: 'Spinach Jade Coin Pendant', seal: 'Coin',
    hook: 'Heaven and earth in a disc with a square hole, in the deep even green that takes the highest polish of any nephrite.' },
  { form: 'pendant_bat_coin', material: 'hetian_white', name: 'Bat and Coin Pendant', seal: 'Blessing',
    hook: 'Blessings arriving, drawn as geometry: one word in Chinese covers both the bat and the blessing.' },
  { form: 'pendant_peach', material: 'yellow_nephrite', name: 'Honey Jade Peach Pendant', seal: 'Peach',
    hook: 'A birthday peach in honey-coloured nephrite, with the stone\'s own colour left as blush on the fruit.' },
  { form: 'pendant_lotus', material: 'jadeite_lavender', name: 'Lavender Jade Lotus Pendant', seal: 'Lotus',
    hook: 'Petals carved thin enough to light from behind, in the one jade colour that only shows itself in daylight.' },
  { form: 'pendant_phoenix', material: 'jadeite_apple', name: 'Apple-Green Phoenix Pendant', seal: 'Phoenix',
    hook: 'A phoenix with its tail cut in openwork — the most demanding form in the repertoire, and half of a traditional pair.' },
  { form: 'pendant_cicada', material: 'jadeite_ice', name: 'Ice Jade Cicada Pendant', seal: 'Cicada',
    hook: 'The oldest jade amulet there is, with wings carved so thin that the stone seems to disappear when you hold it up.' },
  { form: 'pendant_bamboo', material: 'spinach_green', name: 'Spinach Jade Bamboo Pendant', seal: 'Bamboo',
    hook: 'A hollow tube with nodal rings, cut from solid stone — a shape that tolerates no flaw anywhere in the piece.' },
  { form: 'bi_disc', material: 'hetian_white', name: 'White Jade Bi Disc', seal: 'Disc',
    hook: 'The form on which Chinese jade carving was founded, older than the wheel and still the cleanest thing on a desk.' },
  { form: 'bi_disc', material: 'jadeite_moss', name: 'Moss-in-Snow Bi Disc', seal: 'Disc',
    hook: 'A translucent disc veined with green that could not have been planned and could not be repeated.' },
  { form: 'bead_strand', material: 'spinach_green', name: 'Spinach Jade Mala', seal: 'Mala',
    hook: 'A hundred and eight beads graded for consistency, which means cutting several times as many as are used.' },
  { form: 'bead_bracelet', material: 'jadeite_apple', name: 'Apple-Green Jade Bead Bracelet', seal: 'Beads',
    hook: 'A short strand where the whole value is in how closely the beads match each other rather than in any one of them.' },
  { form: 'archers_ring', material: 'black_nephrite', name: 'Black Jade Archer\'s Ring', seal: 'Thumb',
    hook: 'A tool for three thousand years before it was jewellery, and the piece people always ask about.' },
  { form: 'dome_ring', material: 'jadeite_lavender', name: 'Lavender Jade Dome Ring', seal: 'Ring',
    hook: 'A high cabochon on a plain band, which is the setting that puts a lavender stone where the light can find it.' },
  { form: 'signet_seal', material: 'hetian_white', name: 'White Jade Signet Seal', seal: 'Seal',
    hook: 'Your name cut into the base — how a Chinese official signed anything for a thousand years.' },
  { form: 'pair_seal', material: 'yellow_nephrite', name: 'Honey Jade Pair of Seals', seal: 'Seals',
    hook: 'A name seal and a studio seal cut from one block, so the two stones match in tone in a way two singles never do.' },
  { form: 'figure_horse', material: 'hetian_white', name: 'White Jade Horse', seal: 'Horse',
    hook: 'Judged on the line of the neck and the set of the legs, and a good one looks like it is about to move.' },
  { form: 'figure_crane', material: 'mutton_fat', name: 'Mutton-Fat Jade Crane', seal: 'Crane',
    hook: 'Legs cut as thin as the stone allows — which is why a crane can only be carved from flawless material.' },
  { form: 'figure_lion', material: 'spinach_green', name: 'Spinach Jade Guardian Lion', seal: 'Lion',
    hook: 'A dense, compact carving made deliberately from a stone with flaws, because nothing here is thin enough to break.' },
  { form: 'figure_immortal', material: 'hetian_white', name: 'White Jade Immortal', seal: 'Immortal',
    hook: 'One of the Eight Immortals with their attribute in hand: a face and a hand at an inch tall and no way to fix either.' },
  { form: 'toad_on_leaf', material: 'yellow_nephrite', name: 'Honey Jade Toad on a Leaf', seal: 'Toad',
    hook: 'The three-legged toad spitting coins on a lotus leaf, which is where it belongs — on a shop counter.' },
  { form: 'mountain_carving', material: 'hetian_white', name: 'White Jade Mountain Carving', seal: 'Mountain',
    hook: 'A whole boulder carved as the landscape that was already inside it: nothing wasted, nothing imposed.' },
  { form: 'landscape_plaque', material: 'jadeite_moss', name: 'Moss-in-Snow Landscape Plaque', seal: 'River',
    hook: 'The stone\'s green band becomes a river and the carving follows it, which is the only way this form works.' },
  { form: 'cup', material: 'black_nephrite', name: 'Black Jade Cup', seal: 'Cup',
    hook: 'Thin-walled, translucent at the rim, and dense everywhere else — the hardest thing to cut in this material.' },
  { form: 'cup_pair', material: 'spinach_green', name: 'Spinach Jade Pair of Cups', seal: 'Cups',
    hook: 'Two cups from one block so the tone and the wall thickness match, which is far harder than cutting one.' },
  { form: 'snuff_bottle', material: 'mutton_fat', name: 'Mutton-Fat Snuff Bottle', seal: 'Bottle',
    hook: 'Hollowed through a hole no wider than a finger, and judged on the evenness of the hollow rather than the outside.' },
  { form: 'belt_buckle', material: 'hetian_white', name: 'White Jade Belt Buckle', seal: 'Buckle',
    hook: 'A rank marker in the Ming court, and now the least fussy way to wear a large piece of stone.' },
  { form: 'hairpin', material: 'jadeite_ice', name: 'Ice Jade Hairpin', seal: 'Pin',
    hook: 'A tapering shaft that has to be straight and unflawed for its whole length, which is why most stones are rejected first.' },
  { form: 'earrings_drop', material: 'jadeite_apple', name: 'Apple-Green Jade Drop Earrings', seal: 'Drops',
    hook: 'Two drops cut from adjacent slices, so they match at a glance and read greener than a pendant from the same block.' },
  { form: 'earrings_huggie', material: 'jadeite_lavender', name: 'Lavender Jade Huggie Earrings', seal: 'Huggies',
    hook: 'Close against the lobe, so the ear lights the stone from behind — which is what lavender jadeite needs.' },
  { form: 'bangle_oval', material: 'jadeite_moss', name: 'Moss-in-Snow Oval Bangle', seal: 'Bangle',
    hook: 'Cut so the floating green falls where it flatters rather than where it happened to sit in the boulder.' },
  { form: 'bangle_princess', material: 'jadeite_ice', name: 'Ice Jade Princess Bangle', seal: 'Bangle',
    hook: 'Flat inside and out: the profile that wastes least stone, so more of the boulder becomes bangle.' },
  { form: 'bangle_oval', material: 'jadeite_lavender', name: 'Lavender Jade Oval Bangle', seal: 'Bangle',
    hook: 'Follows the wrist rather than the drill core, so it sits closer and moves less than a round bangle.' },
  { form: 'cong_tube', material: 'spinach_green', name: 'Spinach Jade Cong Tube', seal: 'Cong',
    hook: 'A square tube with a round bore, one of the two founding forms of Chinese jade, and its meaning is still unknown.' },
  { form: 'axe_blade', material: 'black_nephrite', name: 'Black Jade Ceremonial Axe', seal: 'Axe',
    hook: 'Too soft in this stone to have ever cut anything — which is exactly why it was ceremonial.' },
  { form: 'dragon_hook', material: 'hetian_white', name: 'White Jade Dragon Hook', seal: 'Hook',
    hook: 'An S-curved belt fastener cut from straight material, which is where a carver\'s sense of depth shows.' },
  { form: 'pendant_chain_set', material: 'jadeite_apple', name: 'Apple-Green Pendant and Chain', seal: 'Chain',
    hook: 'Threaded through a bail drilled in the stone itself, so nothing about a setting competes with the jade.' },
  { form: 'pendant_imperial', material: 'jadeite_imperial', name: 'Imperial Green Jade Pendant', seal: 'Imperial',
    hook: 'A plain cabochon with no carving at all: at this grade the stone is the work, and any cut would remove colour.' },
  { form: 'pendant_guanyin', material: 'jadeite_imperial', name: 'Imperial Green Guanyin Pendant', seal: 'Imperial',
    hook: 'Imperial green spent on a face rather than a cabochon — the rarest combination in the department.' },
  // Added so the department total is a number that reflects the range rather
  // than a round one, and because these are the combinations left in the
  // repertoire: Buddha in two stones it is rarely carved from, a disc in honey
  // jade, a mala in floating-flower, and the working forms in stone that suits
  // them.
  { form: 'pendant_buddha', material: 'jadeite_ice', name: 'Ice Jade Buddha Pendant', seal: 'Buddha',
    hook: 'A seated Buddha in near-colourless ice jadeite, where the carving has nothing to hide behind.' },
  { form: 'pendant_buddha', material: 'yellow_nephrite', name: 'Honey Jade Buddha Pendant', seal: 'Buddha',
    hook: 'A Buddha in honey nephrite, warm enough that the figure reads at arm\'s length.' },
  { form: 'bi_disc', material: 'yellow_nephrite', name: 'Honey Jade Bi Disc', seal: 'Disc',
    hook: 'The oldest form in the repertoire, cut in the rarest of the nephrite colours.' },
  { form: 'bead_strand', material: 'jadeite_moss', name: 'Moss-in-Snow Jade Mala', seal: 'Mala',
    hook: 'A hundred and eight beads of floating-flower jadeite, each one carrying a different pattern.' },
  { form: 'figure_horse', material: 'black_nephrite', name: 'Black Jade Horse', seal: 'Horse',
    hook: 'A horse in black nephrite, where the whole carving is line because there is no colour to carry it.' },
  { form: 'figure_crane', material: 'jadeite_ice', name: 'Ice Jade Crane', seal: 'Crane',
    hook: 'Legs cut thin enough to read as a crane, which only translucent flawless stone allows.' },
  { form: 'cup', material: 'jadeite_apple', name: 'Apple-Green Jade Cup', seal: 'Cup',
    hook: 'Thin-walled jadeite that glows at the rim when you hold it up to the light.' },
  { form: 'bangle_round', material: 'yellow_nephrite', name: 'Honey Jade Round Bangle', seal: 'Bangle',
    hook: 'A round bangle in honey nephrite — one core, so the colour runs the whole way round.' },
  { form: 'pendant_coin', material: 'jadeite_imperial', name: 'Imperial Green Coin Pendant', seal: 'Coin',
    hook: 'Heaven and earth cut from imperial green, which is a great deal of colour for a small object.' },
  { form: 'signet_seal', material: 'jadeite_apple', name: 'Apple-Green Jade Seal', seal: 'Seal',
    hook: 'Bright jadeite cut flat for a seal face, where a flaw would show in every impression.' },
  { form: 'dragon_hook', material: 'jadeite_lavender', name: 'Lavender Jade Dragon Hook', seal: 'Hook',
    hook: 'A belt hook in lavender jadeite, which only shows its colour in daylight.' },
];

/* -------------------------------------------------------------------------- */
/*  Jewellery                                                                 */
/* -------------------------------------------------------------------------- */

/** Metals, stones and pearls, with the price they set. */
export const JEWELLERY_MATERIALS = {
  gold18: {
    name: '18k yellow gold',
    origin: 'Italian and Chinese settings',
    mult: 1,
    copy: 'Eighteen carat, the standard for fine jewellery in both Europe and China: hard enough to hold a setting for decades and warm enough to look like gold rather than brass. We use 18k rather than 24k for anything that holds a stone, because pure gold is too soft to keep a claw tight.',
    price: 620,
  },
  gold22: {
    name: '22k yellow gold',
    origin: 'Traditional Chinese goldsmithing',
    mult: 1.34,
    copy: 'Twenty-two carat, the traditional Chinese standard: deeper in colour, heavier in the hand, and chosen precisely because it is soft enough to be worked by hand into filigree and granulation. It dents where 18k would not, and it is worth the trade if you want gold that looks like gold.',
    price: 880,
  },
  rose: {
    name: '18k rose gold',
    origin: 'Italian and Chinese settings',
    mult: 1.02,
    copy: 'Eighteen carat with copper in the alloy, which gives the warm pink that flatters most skin and, usefully, hides the wear that shows immediately on yellow gold. It is the same hardness as yellow 18k and it does not fade — the colour is in the metal, not a plating.',
    price: 640,
  },
  silver: {
    name: 'sterling silver',
    origin: 'Hand-worked in Yunnan',
    mult: 0.86,
    copy: 'Sterling, 92.5 per cent silver, worked by hand rather than cast. Silver is the metal that lets a workshop do the fine filigree and granulation that would cost four times as much in gold, and it is why you can buy hand-worked metalwork here at this price at all.',
    price: 300,
  },
  filigree: {
    name: 'gold filigree',
    origin: 'Hand-drawn wire, Yunnan',
    mult: 2.2,
    copy: 'Filigree is wire drawn from an ingot by hand, then bent, twisted and soldered into openwork. It is slow enough that a single bracelet can take a smith a fortnight, and impossible to make with a cast because a cast cannot be this fine, this light, or this strong.',
    price: 1900,
  },
  pearl_freshwater: {
    name: 'freshwater pearls',
    origin: 'Zhuji, Zhejiang',
    mult: 1,
    copy: 'Freshwater pearls are the only pearls still available at a price that makes sense for everyday wear, and the quality gap within them is enormous: we buy nacre thickness and lustre, not size, because a thick-nacre freshwater pearl outlasts a thin South Sea one several times over.',
    price: 480,
  },
  pearl_akoya: {
    name: 'Akoya pearls',
    origin: 'Ise-Shima, Japan',
    mult: 1.9,
    copy: 'Akoya is the pearl with the sharpest lustre of any cultured type: a small, round, intensely reflective bead that reads as a mirror rather than a glow. They are graded on nacre thickness and on whether the surface is clean, and a strand is matched bead by bead for both.',
    price: 1180,
  },
  pearl_southsea: {
    name: 'South Sea pearls',
    origin: 'Broome, Western Australia',
    mult: 3.1,
    copy: 'South Sea pearls are large, warm-toned and grown in a Pinctada maxima oyster that takes years to produce a single bead. The size is not the achievement — the achievement is a thick nacre and a surface with no blemish across a bead that size. A matched strand is assembled from hundreds of loose pearls.',
    price: 2600,
  },
  diamond: {
    name: 'diamonds',
    origin: 'Brilliant-cut, conflict-free',
    mult: 2.6,
    copy: 'Conflict-free brilliant cuts, graded on the usual four axes and supplied with their certificates. We buy on cut rather than on carat, because a well-cut smaller stone returns more light than a badly cut larger one, and the difference is visible across a room.',
    price: 2200,
  },
  ruby: {
    name: 'rubies',
    origin: 'Mogok, Myanmar',
    mult: 2.4,
    copy: 'Burmese ruby from the Mogok stone tract, the origin that set the standard for the colour: a red with a faint blue undertone that reads as a lit coal rather than as a pink stone. Any ruby this colour from anywhere else costs more and pleases less.',
    price: 2000,
  },
  sapphire: {
    name: 'sapphires',
    origin: 'Ratnapura, Sri Lanka',
    mult: 2.2,
    copy: 'Sri Lankan sapphires, chosen for saturation rather than for size, because a sapphire is a colour before it is a carat weight. The blue we buy has the slight violet edge that keeps it alive indoors, where most sapphires go grey.',
    price: 1800,
  },
  jade_cab: {
    name: 'jadeite cabochons',
    origin: 'Hpakant, Kachin State, Myanmar',
    mult: 1.6,
    copy: 'Jadeite cut as plain cabochons for setting, because a set stone is judged on colour and translucency and any carving would remove both. Each cabochon is cut to match its partner rather than to a size, so a pair costs more than twice a single.',
    price: 1200,
  },
  tourmaline: {
    name: 'tourmalines',
    origin: 'Mogok, Myanmar',
    mult: 1.7,
    copy: 'Tourmaline comes in more colours than any other gemstone, and the stones we use are the warm pink-reds that hold their colour under both daylight and lamplight. It is a hard enough stone to wear daily, which is not true of many coloured gems at this price.',
    price: 1400,
  },
  amber: {
    name: 'Baltic amber',
    origin: 'Kaliningrad, Baltic coast',
    mult: 1.3,
    copy: 'Baltic amber, fossilised resin roughly forty million years old, warm to the touch in a way no stone is. It is soft — a fingernail will mark it — and it is worn continuously by people who like that it is alive to the skin.',
    price: 900,
  },
  coral: {
    name: 'Mediterranean coral',
    origin: 'Sardinia, sourced under permit',
    mult: 1.44,
    copy: 'Mediterranean coral, cut from a branch rather than a stone, so the pieces are irregular by nature and matched pairs take hunting. Everything we sell is documented under a sustainable-harvest permit, which is not true of most coral on the market.',
    price: 1050,
  },
  moonstone: {
    name: 'rainbow moonstone',
    origin: 'Ratnapura, Sri Lanka',
    mult: 1.36,
    copy: 'Moonstone with the blue adularescence that gives the stone its name: an internal sheen that moves across the surface as you turn it. It is a comparatively soft stone and it is cut as a cabochon for exactly that reason.',
    price: 940,
  },
  garnet: {
    name: 'garnets',
    origin: 'Mogok, Myanmar',
    mult: 1.18,
    copy: 'Garnets are the underrated coloured stone: hard, durable, and a red with genuine depth rather than the flat brown that cheap garnets have. The stones we use are the rhodolite reds that sit between ruby and amethyst.',
    price: 800,
  },
  lapis: {
    name: 'lapis lazuli',
    origin: 'Badakhshan, Afghanistan',
    mult: 1.24,
    copy: 'Lapis lazuli from the Afghan deposits that have been worked for six thousand years, chosen for a deep even blue with a light scatter of pyrite rather than none at all — the pyrite is what tells you the stone is real.',
    price: 860,
  },
  turquoise: {
    name: 'turquoise',
    origin: 'Hubei, China',
    mult: 1.14,
    copy: 'Hubei turquoise with a tight, even blue and a fine dark matrix, cut as cabochons. Only a small fraction of turquoise is hard enough to hold a polish without being stabilised, and this is that fraction.',
    price: 780,
  },
};

/** Jewellery forms. */
export const JEWELLERY_FORMS = {
  ring_solitaire: {
    name: 'solitaire ring',
    copy: 'A single stone on a plain band: the setting with nothing to hide behind, where the cutting of the stone and the evenness of the claws are the whole object.',
    care: 'Have the claws checked annually if the ring is worn daily.',
    unit: 'Ring',
  },
  ring_halo: {
    name: 'halo ring',
    copy: 'A centre stone surrounded by a ring of smaller ones, which enlarges the apparent size of the centre without enlarging the centre. The skill is in matching the halo so the light from the stones reads as one instead of as a row.',
    care: 'The small settings collect soap; clean with a soft brush.',
    unit: 'Ring',
  },
  ring_cabochon: {
    name: 'cabochon ring',
    copy: 'A smooth, unfaceted stone on a raised band, which is the setting that suits a stone with colour and translucency but no brilliance — jade, turquoise, amber, coral.',
    care: 'Cabochons are softer than facets; avoid knocking the dome.',
    unit: 'Ring',
  },
  ring_signet: {
    name: 'signet ring',
    copy: 'A solid flat-topped ring made to carry an engraved crest or monogram, heavy enough to sit flat on the hand. We can engrave it here, or leave the face plain if you would rather it stayed quiet.',
    care: 'Engraving can be added or deepened at any time.',
    unit: 'Ring',
  },
  ring_stack: {
    name: 'stacking ring',
    copy: 'A narrow ring made to be worn in a group, so the band is cut thin and the stone set low enough to sit against its neighbours without catching.',
    care: 'Wear it against rings of similar hardness; softer stones scratch.',
    unit: 'Ring',
  },
  necklace_strand: {
    name: 'bead strand necklace',
    copy: 'A full strand matched bead by bead for size, colour and lustre, which is a selection exercise rather than a setting one: a strand of forty pearls takes several hundred to assemble.',
    care: 'Restring on silk every few years if worn regularly.',
    unit: 'Necklace',
  },
  necklace_pendant: {
    name: 'pendant necklace',
    copy: 'A pendant on a fine chain, weighted so it hangs where the collarbone catches the light. The chain carries as much of the design as the stone does at this scale.',
    care: 'Check the clasp and the jump ring each season.',
    unit: 'Necklace',
  },
  necklace_beaded: {
    name: 'beaded necklace',
    copy: 'A necklace strung from cut beads rather than a single pendant, which means the grading discipline of a pearl strand applied to stone: colour and size have to hold from the first bead to the last.',
    care: 'Restring on silk every few years; knots protect against loss.',
    unit: 'Necklace',
  },
  necklace_choker: {
    name: 'choker',
    copy: 'A close-fitting neckpiece, which is the hardest length to make comfortable: it has to move with the throat rather than against it, so the linking and the weight are the design.',
    care: 'Check the clasp before each wear; a choker fails suddenly.',
    unit: 'Necklace',
  },
  necklace_lariat: {
    name: 'lariat',
    copy: 'An open-ended necklace that fastens through itself rather than at the back, so it can be worn at any length and adjusted in a second. It is the most adaptable form here.',
    care: 'The open end is the weak point; avoid snagging it on clasps.',
    unit: 'Necklace',
  },
  earrings_stud: {
    name: 'stud earrings',
    copy: 'A matched pair set directly on the lobe with nothing hanging, which makes them the most-worn earring and the one where the match between the two stones matters most.',
    care: 'Clean the posts; studs collect skin oils at the setting.',
    unit: 'Earrings',
  },
  earrings_drop: {
    name: 'drop earrings',
    copy: 'A stone hanging below the lobe so light passes through it, which reads brighter and deeper than a stud cut from the same material.',
    care: 'Hooks or posts are available; ask when ordering.',
    unit: 'Earrings',
  },
  earrings_hoop: {
    name: 'hoop earrings',
    copy: 'A complete circle in metal, worked so the hoop is even all the way round, which is a harder thing to make by hand than a straight band.',
    care: 'Store them hanging rather than flat so the hoops keep their shape.',
    unit: 'Earrings',
  },
  earrings_chandelier: {
    name: 'chandelier earrings',
    copy: 'A graduated arrangement of stones on a frame, built to move: the drops are deliberately hung on articulation so the whole piece shifts with the head rather than sitting rigid.',
    care: 'Articulated links dislike being stored tangled; use the box.',
    unit: 'Earrings',
  },
  bracelet_link: {
    name: 'link bracelet',
    copy: 'A bracelet built from individual links soldered one at a time, so the whole piece articulates and lies against the wrist instead of standing off it.',
    care: 'Check the clasp and the end links each season.',
    unit: 'Bracelet',
  },
  bracelet_beaded: {
    name: 'beaded bracelet',
    copy: 'A short strand of matched beads, graded exactly like a necklace but in a length that sits on the wrist and rolls as you move.',
    care: 'Restring if the cord shows wear.',
    unit: 'Bracelet',
  },
  bracelet_bangle: {
    name: 'bangle',
    copy: 'A closed circle with no clasp, slipped over the hand, which means the fit is fixed and the size is chosen once. Nothing about it can work loose, which is why a bangle is the bracelet people wear continuously.',
    care: 'Sized to slip over the knuckles; measure before ordering.',
    unit: 'Bracelet',
  },
  cuff: {
    name: 'cuff',
    copy: 'An open band that grips the wrist by tension alone, so it can be adjusted by a jeweller but not by the wearer, and it has no clasp to fail.',
    care: 'Have it adjusted by a jeweller rather than bending it yourself.',
    unit: 'Cuff',
  },
  tennis: {
    name: 'tennis bracelet',
    copy: 'A single line of matched stones set in a continuous row, linked so the bracelet articulates between every stone. Matching the stones along the line is the entire exercise.',
    care: 'Have the links and clasp checked annually.',
    unit: 'Bracelet',
  },
  brooch: {
    name: 'brooch',
    copy: 'A pin with a proper double catch, which is the piece that lets a stone be worn on wool or silk where no chain would sit right. Brooches have come back largely because nothing else can do this.',
    care: 'A double catch is fitted as standard; check it closes fully.',
    unit: 'Brooch',
  },
  pendant: {
    name: 'pendant',
    copy: 'A stone on its own bail, sold to be worn on a chain you already own, or with one added here.',
    care: 'Check the bail and jump ring each season.',
    unit: 'Pendant',
  },
  hairpin: {
    name: 'hairpin',
    copy: 'A pin worked to hold in hair rather than to sit on a lapel: the shaft is tapered and slightly sprung so it grips, which is a detail that separates a hairpin from a brooch on a stick.',
    care: 'The shaft is sprung by design; do not straighten it.',
    unit: 'Hairpin',
  },
  anklet: {
    name: 'anklet',
    copy: 'A short chain worn at the ankle, deliberately built lighter than a bracelet because an anklet is not under the same tension and should not feel like it.',
    care: 'Lighter chain than a bracelet; check the links each season.',
    unit: 'Anklet',
  },
  set: {
    name: 'matched set',
    copy: 'Necklace, earrings and bracelet cut from one parcel of stones so the three match in tone, which is a matched suite rather than three separate purchases put together.',
    care: 'Store the three together so they age at the same rate.',
    unit: 'Set',
  },
  locket: {
    name: 'locket',
    copy: 'A hinged case built to hold something, with a proper hinge and a catch that closes flush — the two details that separate a locket that lasts from one that does not.',
    care: 'Test the hinge gently; do not force the case open.',
    unit: 'Locket',
  },
};

/** form_key, material_key, name, hook, plus optional price/size overrides. */
export const JEWELLERY_ROWS = [
  { form: 'ring_solitaire', material: 'diamond', name: 'Solitaire Diamond Ring', seal: 'Solitaire',
    hook: 'One brilliant on a plain band: nothing to hide behind, so the cut of the stone is the whole object.' },
  { form: 'ring_halo', material: 'diamond', name: 'Halo Diamond Ring', seal: 'Halo',
    hook: 'A halo that matches the centre so closely the light reads as one stone rather than as a ring of them.' },
  { form: 'ring_halo', material: 'sapphire', name: 'Sapphire and Diamond Halo Ring', seal: 'Sapphire',
    hook: 'A violet-edged blue that stays blue indoors, which is where most sapphires go grey.' },
  { form: 'ring_halo', material: 'ruby', name: 'Burmese Ruby Halo Ring', seal: 'Ruby',
    hook: 'Mogok ruby with the faint blue undertone that makes the red read as a lit coal rather than a pink stone.' },
  { form: 'ring_cabochon', material: 'jade_cab', name: 'Jadeite Cabochon Ring', seal: 'Jade',
    hook: 'A plain dome of jadeite, set high, because a carved stone would lose the colour you are paying for.' },
  { form: 'ring_cabochon', material: 'turquoise', name: 'Hubei Turquoise Ring', seal: 'Turquoise',
    hook: 'Tight, even blue with a fine dark matrix — the matrix is how you know the stone is real.' },
  { form: 'ring_cabochon', material: 'amber', name: 'Baltic Amber Ring', seal: 'Amber',
    hook: 'Warm to the touch in a way no stone is, from resin that set forty million years ago.' },
  { form: 'ring_cabochon', material: 'moonstone', name: 'Rainbow Moonstone Ring', seal: 'Moonstone',
    hook: 'A sheen that slides across the surface as you turn the hand rather than sitting still like a facet.' },
  { form: 'ring_signet', material: 'gold18', name: 'Engraved Signet Ring', seal: 'Signet',
    hook: 'Heavy enough to sit flat on the hand, with the face left plain or cut with your own mark.' },
  { form: 'ring_stack', material: 'garnet', name: 'Garnet Stacking Ring', seal: 'Garnet',
    hook: 'A rhodolite red with real depth rather than the flat brown cheap garnets have, cut thin to sit against its neighbours.' },
  { form: 'necklace_strand', material: 'pearl_freshwater', name: 'Freshwater Pearl Necklace', seal: 'Pearl',
    hook: 'Bought on nacre thickness and lustre rather than size, because a thick-nacre freshwater pearl outlasts a thin saltwater one.' },
  { form: 'necklace_strand', material: 'pearl_akoya', name: 'Akoya Pearl Necklace', seal: 'Akoya',
    hook: 'Matched bead by bead on both nacre depth and surface cleanliness: a mirror rather than a glow.' },
  { form: 'necklace_strand', material: 'pearl_southsea', name: 'South Sea Pearl Necklace', seal: 'South Sea',
    hook: 'Large, warm-toned and unblemished across a bead grown over years in a single oyster, assembled from hundreds.' },
  { form: 'necklace_pendant', material: 'diamond', name: 'Diamond Pendant Necklace', seal: 'Pendant',
    hook: 'A single brilliant on a fine chain, weighted so it hangs exactly where the collarbone catches the light.' },
  { form: 'necklace_pendant', material: 'jade_cab', name: 'Jadeite Pendant Necklace', seal: 'Jade',
    hook: 'A jadeite drop on a fine gold chain, with the cabochon cut to match the tone of the metal.' },
  { form: 'necklace_pendant', material: 'tourmaline', name: 'Tourmaline Pendant Necklace', seal: 'Tourmaline',
    hook: 'A warm pink-red that holds its colour under lamplight as well as daylight, which is not true of most pink stones.' },
  { form: 'necklace_beaded', material: 'lapis', name: 'Lapis Beaded Necklace', seal: 'Lapis',
    hook: 'Deep Afghan blue with a light scatter of pyrite, strung so the colour holds from the first bead to the last.' },
  { form: 'necklace_beaded', material: 'jade_cab', name: 'Jadeite Beaded Necklace', seal: 'Jade',
    hook: 'Cut beads graded in the round, which means matching colour, size and translucency across every bead on the strand.' },
  { form: 'necklace_beaded', material: 'coral', name: 'Coral Beaded Necklace', seal: 'Coral',
    hook: 'Cut from branch rather than stone, so the beads are naturally irregular and matching a strand takes hunting.' },
  { form: 'necklace_choker', material: 'pearl_akoya', name: 'Akoya Pearl Choker', seal: 'Akoya',
    hook: 'Built to move with the throat rather than against it, which is what makes a choker wearable rather than a collar.' },
  { form: 'necklace_choker', material: 'gold22', name: '22k Gold Choker', seal: 'Gold',
    hook: 'Soft enough to be worked by hand and heavy enough to sit still, in the traditional Chinese standard.' },
  { form: 'necklace_lariat', material: 'pearl_freshwater', name: 'Pearl Lariat', seal: 'Lariat',
    hook: 'Open-ended and threaded through itself, so it is adjustable to any length in a second and has no clasp to fail.' },
  { form: 'earrings_stud', material: 'diamond', name: 'Diamond Stud Earrings', seal: 'Studs',
    hook: 'A matched pair set directly on the lobe, which is where the match between the two stones shows most.' },
  { form: 'earrings_stud', material: 'pearl_akoya', name: 'Akoya Pearl Studs', seal: 'Studs',
    hook: 'Two beads matched on lustre rather than on millimetres, because lustre is what you see from a conversation away.' },
  { form: 'earrings_stud', material: 'jade_cab', name: 'Jadeite Stud Earrings', seal: 'Studs',
    hook: 'A pair of jadeite cabochons cut to match each other, not to a size — which is why a pair costs more than two singles.' },
  { form: 'earrings_drop', material: 'tourmaline', name: 'Tourmaline Drop Earrings', seal: 'Drops',
    hook: 'Hanging below the lobe so light passes through the stone, which reads deeper than a stud of the same material.' },
  { form: 'earrings_drop', material: 'amber', name: 'Amber Drop Earrings', seal: 'Drops',
    hook: 'Almost weightless for their size, which is the whole reason amber works as a drop where stone would drag.' },
  { form: 'earrings_hoop', material: 'gold18', name: '18k Gold Hoop Earrings', seal: 'Hoops',
    hook: 'A complete circle worked even all the way round, which is harder by hand than a straight band.' },
  { form: 'earrings_chandelier', material: 'diamond', name: 'Diamond Chandelier Earrings', seal: 'Chandelier',
    hook: 'Built on articulated links so the drops shift with the head instead of standing rigid.' },
  { form: 'bracelet_link', material: 'gold18', name: '18k Gold Link Bracelet', seal: 'Links',
    hook: 'Individual links soldered one at a time, so it lies against the wrist instead of standing off it.' },
  { form: 'bracelet_beaded', material: 'jade_cab', name: 'Jadeite Beaded Bracelet', seal: 'Beads',
    hook: 'Graded like a necklace but in a length that rolls as you move, which is the appeal of a bead bracelet.' },
  { form: 'bracelet_bangle', material: 'gold22', name: '22k Gold Bangle', seal: 'Bangle',
    hook: 'A closed circle with no clasp, so nothing can work loose — which is why a bangle is worn continuously.' },
  { form: 'cuff', material: 'filigree', name: 'Filigree Lace Cuff', seal: 'Filigree',
    hook: 'Wire drawn from an ingot by hand and soldered into openwork fine enough to read as lace — a fortnight of work that no cast can reproduce.' },
  { form: 'tennis', material: 'diamond', name: 'Diamond Tennis Bracelet', seal: 'Tennis',
    hook: 'One line of matched stones linked between every setting, with the matching being the entire exercise.' },
  { form: 'brooch', material: 'coral', name: 'Coral Brooch', seal: 'Brooch',
    hook: 'A branch of Mediterranean coral on a double catch — the piece that lets colour be worn on wool or silk.' },
  { form: 'brooch', material: 'amber', name: 'Amber Brooch', seal: 'Brooch',
    hook: 'Lit from behind by whatever you are wearing, which is what amber does that no opaque stone can.' },
  { form: 'pendant', material: 'ruby', name: 'Burmese Ruby Pendant', seal: 'Ruby',
    hook: 'A single Mogok ruby on its own bail, sold to hang on a chain you already own.' },
  { form: 'pendant', material: 'moonstone', name: 'Moonstone Pendant', seal: 'Moonstone',
    hook: 'An adularescent cabochon with the blue sheen moving across it, hung so the light can reach both faces.' },
  { form: 'hairpin', material: 'gold22', name: '22k Gold Hairpin', seal: 'Hairpin',
    hook: 'A tapered, slightly sprung shaft that grips the hair, which is what separates a hairpin from a brooch on a stick.' },
  { form: 'anklet', material: 'silver', name: 'Silver Anklet', seal: 'Anklet',
    hook: 'Deliberately lighter than a bracelet, because an anklet is not under the same tension and should not feel like it.' },
  { form: 'set', material: 'pearl_freshwater', name: 'Pearl Suite', seal: 'Suite',
    hook: 'Necklace, earrings and bracelet from one parcel, so the three match in tone rather than nearly matching.' },
  { form: 'locket', material: 'gold18', name: '18k Gold Locket', seal: 'Locket',
    hook: 'A hinged case with a proper hinge and a catch that closes flush, which is what separates a locket that lasts from one that does not.' },
  { form: 'locket', material: 'silver', name: 'Silver Locket', seal: 'Locket',
    hook: 'Hand-worked sterling with a tested hinge, built to be opened often rather than once.' },
  // Three more, for the same reason as the jade additions above.
  { form: 'necklace_pendant', material: 'pearl_southsea', name: 'South Sea Pearl Pendant', seal: 'Pearl',
    hook: 'A single large South Sea pearl on a fine chain, where the whole piece is the bead.' },
  { form: 'bracelet_bangle', material: 'silver', name: 'Sterling Silver Bangle', seal: 'Bangle',
    hook: 'A closed circle in hand-worked sterling, with no hinge and nothing to work loose.' },
  { form: 'ring_signet', material: 'gold22', name: '22k Gold Signet Ring', seal: 'Signet',
    hook: 'Twenty-two carat, the traditional Chinese standard: soft enough to engrave deeply by hand.' },
];
